library(tidyverse)
data("starwars")
starwars %>% select(-name)
starwars %>% select(starts_with("s"))
homeworld <- starwars %>% select(name, homeworld)
human <- starwars %>% filter(species == "Human")
starwars %>% filter(species == "Human", homeworld == "Tatooine")
starwars_nodroids <- starwars %>% filter(species != "Droid")
starwars %>% group_by(species) %>% tally()
starwars %>% group_by(species, gender) %>% tally()
table_gender.species <- starwars %>% group_by(species, gender) %>% tally()
starwars %>% group_by(species) %>% summarise(mean_height = mean(height, na.rm = T),mean_mass = mean(mass,na.rm = T))
?sd()
starwars %>% group_by(species) %>% summarise(mean_height = mean(height, na.rm = T),mean_mass = mean(mass,na.rm = T))
starwars %>% group_by(species) %>% summarise(mean_height = sd(height, na.rm = T),sd_mass = sd(mass,na.rm = T))
ggplot(starwars, aes(height, mass)) + geom_point()
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red")
ggplot(starwars, aes(height, mass)) + geom_point(colour = "purple", pch = 3)
ggplot(starwars, aes(height, mass)) + geom_point(colour = "red") + theme_light()
starwars.gráfico <- starwars %>% filter(species != "Hutt")
ggplot(starwars.gráfico, aes(height, mass)) + geom_point(colour = "blue")
toy <- read_csv("Descargas/toy.csv")
toy <- read_csv("C:/Users/Usuario/Downloads/toy.csv") 
toy %>% group_by(Sex) %>% summarise(mean_Height_cm = mean(Height_cm, na.rm = T),mean_Weight_Kg = mean(Weight_Kg,na.rm = T),mean_IMC = mean(IMC,na.rm = T),mean_IAS = mean(IAS,na.rm = T),mean_Ccintura = mean(Ccintura,na.rm = T))
toy1 <- toy %>% group_by(Sex) %>% summarise(mean_Height_cm = mean(Height_cm, na.rm = T),mean_Weight_Kg = mean(Weight_Kg,na.rm = T),mean_IMC = mean(IMC,na.rm = T),mean_IAS = mean(IAS,na.rm = T),mean_Ccintura = mean(Ccintura,na.rm = T))
toy4 <- toy %>% filter(Sex == "Women")
toy5 <- toy4 %>% filter(IMC_clas == "Overweight")
ggplot(toy, aes(IMC, Weight_Kg)) + geom_point(colour = "orange")
toy6 <- toy %>% filter(IMC_clas != "Normal")
ggplot(toy6, aes(IMC, Weight_Kg)) + geom_point(colour = "green")
install.packages("ape")
install.packages("phangorn")
install.packages("phytools")
